### ISSUE TITLE
Completely blocking endless room

### ISSUE THREAD

**Issue by TimePause3D** [DDNetPP/maps#95] opened 2022-05-02 10:12 UTC
Endless is a really powerful weapon in this mod.
So I came with an idea, to block the portal way to endless completely by placing collision tile in this red square.
![image](https://user-images.githubusercontent.com/85745286/166218650-bdd21819-5032-40d7-bc10-7ffb4d78afb1.png)
This will make people go traditional way through superroom etc.
By blocking this path to endless, we could get rid of small pay to win for people having a portal gun
Let me know what u think :D

**Comment by ChillerDragon** [comment] 2022-05-02 10:14
Yea sounds nice. @fokkonaut opinions?

**Comment by joohnes** [comment] 2022-05-02 10:25
buying portal gun would be money waste then (as buying vip is), so how would fokko pay off the server? Anyway, great idea

**Comment by TimePause3D** [comment] 2022-05-02 10:37
The portal gun has many uses like transporting or even combat. It doesn't have only one purpose of going to the endless room.
I don't think it will go to waste, because it makes traveling around the map much easier.

**Comment by joohnes** [comment] 2022-05-02 10:45
That's true, you're making a good point, but undeniably getting endless is it's most common use. Also, i support your idea, as fighting against full bonus is quite annoying

**Comment by itubetw** [comment] 2022-05-02 14:10
If there were such a thing, you would change the whole server. Either in the positive or in the negative. I am in favour of it remaining as it is. But the idea could be implemented differently. Namely that there is a more difficult and harder way for Portal Gun User. What do you think? :o

**Comment by TimePause3D** [comment] 2022-05-02 14:47
Fokkonaut had an intention to make endless hook only accessible the traditional way (thats why the entrance to it has been blocked on spawn). Fokkonaut could made an oversight by not blocking the portal way or he just didn't know about that.
I think it would be the best making the portal path inaccessible, because it's already pay to win :D.

**Comment by TimePause3D** [comment] 2022-05-02 14:56
@Itube17 I dont think implementing a second harder way (Portal way you are talking about) would be good idea, when we already have working one :D

**Comment by ChillerDragon** [comment] 2022-05-03 10:59
> Fokkonaut had an intention to make endless hook only accessible the traditional way (thats why the entrance to it has been blocked on spawn). Fokkonaut could made an oversight by not blocking the portal way or he just didn't know about that. I think it would be the best making the portal path inaccessible, because it's already pay to win :D.

Yes it was intended to close the portal cut. And also make portal users go the "normal" way. It still is easier to get into magic room and do the special race with portal. And the edge cut was overseen. But it seemed annoyingly hard enough in the beginning so it was kept.

Since it is now common meta and most portal users can do it somewhat consistent we should maybe close it. I assumed that it is so annoying that portal users would still occasionally go the longer way. But that did not turn out to be the case. So currently endless is still very risk and effort free reachable for portal users. Which is not too nice for the overall amount of endless players on the server. But I would even argue that it is annoying for the portal users. Since its the fastest and safest way to obtain endless, portal players striving for effectivity are forced to fiddle around with this annoying edge.

**Comment by itubetw** [comment] 2022-05-30 15:38
> Endless is a really powerful weapon in this mod. So I came with an idea, to block the portal way to endless completely by placing collision tile in this red square. ![image](https://user-images.githubusercontent.com/85745286/166218650-bdd21819-5032-40d7-bc10-7ffb4d78afb1.png) This will make people go traditional way through superroom etc. By blocking this path to endless, we could get rid of small pay to win for people having a portal gun Let me know what u think :D


![screenshot_2022-05-30_16-52-35](https://user-images.githubusercontent.com/91550686/171024942-c94bf52c-0ee8-4982-b699-84f9457c047c.png)
i did an example for chillerdragon cause i think hes to lazy to do the map update. I made a farm spot that the spot is not useless.

**Comment by ChillerDragon** [comment] 2022-07-27 10:05
done

**Closed as completed by ChillerDragon** 2022-07-27 10:05 UTC
